### ISSUE TITLE
Can't connect with my application credential after version 1.13.4

### ISSUE THREAD

**Issue by Safirion** [isaiahwilliams/partner-center-dotnet#13]
Hi,

To connect to the partner center I use this code :
```
PartnerService.Instance.ApiRootUrl = new Uri(Configurations.Authentication.PartnerServiceApiRoot);
IPartnerCredentials partnerCredentials = await PartnerCredentials.GenerateByApplicationCredentialsAsync(Configurations.Authentication.ApplicationId, Configurations.Authentication.ApplicationSecret, Configurations.Authentication.ApplicationDomain, Configurations.Authentication.Authority, Configurations.Authentication.ResourceUrl, RequestContextFactory.Create("fr-FR"));
_aggregatePartner = PartnerService.Instance.CreatePartnerOperations(partnerCredentials); 
```

And in this is my configuration : 
```
"Authentication": {
        "ApplicationId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxx",
        "ApplicationSecret": "xxxxxxxxxxx/xxxxxxxxxxxxxxxxxx=", 
        "ApplicationDomain": "xxxxxxxxx.onmicrosoft.com",
        "Authority": "https://login.windows.net",
        "ResourceUrl": "https://graph.windows.net",
        "PartnerServiceApiRoot": "https://api.partnercenter.microsoft.com"
      }
```

With the version **1.13.4** of PartnerCenter, **all is good**, I can interact with my customers, etc...
But if I update the nuget package to **1.13.5 or later**, I have some **errors** like
`Authority should be in the form <host>/<audience>` and even if I replace my authority configuration by `https://login.microsoftonline.com/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxx/` (where xxx is my tenant Id), login was fine but after I have "Access unauthorized" when I want to list customer for exemple.

Is there any documentation about this change or a new procedure for the connection ?

Thanks by advance

**Comment by isaiahwilliams** [comment]
Hi @Safirion, 

Thank you for sharing this information let me look into what is happening, and I will get back with you shortly.

**Comment by isaiahwilliams** [comment]
Hi @Safirion, 

This issue will be fixed with the release of version 1.14.1 which will released tonight.

**Comment by Safirion** [comment]
Thank you for your reply and for the patch 👍

**Comment by isaiahwilliams** [comment]
Everything should be
